---
- hosts: base_endpoint
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Add cloud user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: true

    - name: Allow HTTP pulling from private docker registry
      shell: echo '{ "insecure-registries":["{{ registry_ip }}"] }' > /etc/docker/daemon.json

    - name: Restart docker service
      command: systemctl restart docker

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Make sure swap is disabled even after reboot
      command: sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Enable ipv4 forwarding
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

    - name: Reload ip settings
      command: sysctl -p

    - name: Install Mosquitto
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - mosquitto=1.6.9-1
