---
- hosts: localhost
  connection: local
  tasks:
    - name: Checkout Opencraft
      git:
        repo: 'git@github.com:atlarge-research/opencraft-dev.git'
        version: 'dev'
        dest: '/tmp/opencraft'

    - name: Copy configuration file to server directory
      copy:
        src: './opencraft.yml'
        dest: '/tmp/opencraft/opencraft.yml'
        remote_src: true

    - name: Copy start file to server directory
      copy:
        src: './start.sh'
        dest: '/tmp/opencraft/start.sh'
        remote_src: true

    - name: Change image to Alpine # Amazon Linux 2 does not have tools installed to kill processes
      lineinfile:
        path: '/tmp/opencraft/Dockerfile'
        search_string: 'FROM amazoncorretto:8'
        line: 'FROM amazoncorretto:8-alpine'

    - name: Add configuration file to dockerfile
      blockinfile:
        path: '/tmp/opencraft/Dockerfile'
        insertbefore: 'CMD ["java", "-jar", "opencraft.jar"]'
        block: |
            COPY --from=builder /usr/src/opencraft/start.sh /usr/local/bin/start.sh
            RUN chmod +x /usr/local/bin/start.sh
            COPY ./opencraft.yml /config/opencraft.yml

    - name: Output server values # Amazon Linux 2 does not have tools installed to kill processes
      lineinfile:
        path: '/tmp/opencraft/Dockerfile'
        search_string: 'CMD ["java", "-jar", "opencraft.jar"]'
        line: 'CMD ["start.sh"]'


    - name: Build and push image
      shell:
        cmd: 'docker buildx build --platform linux/amd64 -t lwagner1/opencraft_benchmark:opencraft_server --push .'
        chdir: '/tmp/opencraft'
