---
- hosts: cloudcontroller
  become: true
  tasks:
    - name: Create job file
      shell: |
        cat > "/home/{{ username }}/client.yaml" <<EOF
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{ app_name }}
        spec:
          template:
            metadata:
              name: {{ app_name }}
            spec:
              containers:
              - name: {{ app_name }}
                image: {{ image }}
                imagePullPolicy: {{ pull_policy }}
                resources:
                  requests:
                    memory: "{{ memory_client }}Mi"
                    cpu: {{ cpu_client }}
                env:
                - name: SLEEP_TIME
                  value: "{{ sleep_time }}"
              restartPolicy: Never
              nodeSelector:
                kubernetes.io/hostname: {{ node_client }}
        EOF

    - name: Launch job
      command: >
        kubectl apply -f "/home/{{ username }}/client.yaml"
