---
- hosts: clouds
  become: true
  tasks:
    - name: Run Mosquitto
      command: mosquitto -d -p 1883

    - name: Forward IPv4 and let iptables see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

        sudo modprobe overlay
        sudo modprobe br_netfilter

        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF

        sudo sysctl --system

    - name: Wait for join command to be finished on cloud controller
      local_action:
        module: wait_for
        path: "{{ continuum_home }}/join-command.txt"
      become: false

    - name: Copy the join command to the cloud node
      copy:
        src: "{{ continuum_home }}/join-command.txt"
        dest: /tmp/join-command.txt

    - name: Make the join command file executable
      file:
        dest: /tmp/join-command.txt
        mode: +x

    - name: Add ignore errors flag
      command: sed -i '${s/$/ --ignore-preflight-errors all/}' /tmp/join-command.txt

    - name: Execute the join command
      shell: bash /tmp/join-command.txt

    - name: Remove unneeded KubeEdge join command file
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/join-command.txt
