---
- name: Install Kata runtime components
  hosts: clouds:edges
  become: true
  roles:
    - role: kata_containers

- name: Register Kata runtime classes
  hosts: cloudcontroller
  become: true
  roles:
    - role: kata_runtime_classes
