schema_version: 1
kind: ContinuumSoftware

software:
  modules:
    - id: orchestrator-main
      type: kubernetes
      assign_to: { match: { cluster: cloud-1 } }
      config:
        kube_version: "v1.27.0"
        cache_worker: false
        # kube_deployment: pod          # Optional for kubernetes/kubecontrol/kube_kata
        # runtime: kata-qemu            # kube_kata only
        # runtime_filesystem: devmapper # kube_kata only

    - id: endpoint-runtime
      type: endpoint_runtime
      assign_to: { match: { cluster: endpoint-1 } }
      config: {}

    - id: observability-main
      type: observability
      assign_to: { match: { cluster: cloud-1 } }
      config: {}
