---
- name: Install common infrastructure software on base VMs
  hosts: "{{ continuum_common_base_hosts | default('base') }}"
  become: true
  roles:
    - role: netperf
    - role: mahimahi
      when: continuum_enable_mahimahi | default(false)
