---
- hosts: cloudcontroller
  become: true
  tasks:
    - name: Create job directory
      file:
        path: /home/{{ username }}/jobs
        state: directory

    - name: Add container descriptions
      shell: |
        for i in `seq 1 {{ replicas }}`
        do
          cat > "/home/{{ username }}/jobs/job-$i.yaml" <<EOF
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: {{ app_name }}-$i
        spec:
          template:
            metadata:
              name: {{ app_name }}-$i
            spec:
              restartPolicy: Never
              containers:
              - name: {{ app_name }}-$i
                image: {{ image }}
                imagePullPolicy: {{ pull_policy }}
                resources:
                  requests:
                    memory: "{{ memory_req }}Mi"
                    cpu: {{ cpu_req }}
                env:
                - name: SLEEP_TIME
                  value: "{{ sleep_time }}"
        EOF
        done
