---
- name: Launch benchmark for kubecontrol stress pod
  hosts: cloudcontroller
  become: true
  roles:
    - role: k8s_job_deploy
      vars:
        app_k8s_job_deploy_layout: single_parallel
        app_k8s_job_deploy_resources_enabled: false
        app_k8s_job_deploy_env:
          - name: TIMEOUT
            value: "{{ stress_app_timeout }}"
