---
- name: Launch benchmark for kubecontrol with one call total, using one file per job
  hosts: cloudcontroller
  become: true
  roles:
    - role: k8s_job_deploy
      vars:
        app_k8s_job_deploy_layout: one_file_per_job
        app_k8s_job_deploy_index_template_metadata: true
        app_k8s_job_deploy_index_container_name: true
        app_k8s_job_deploy_env:
          - name: SLEEP_TIME
            value: "{{ sleep_time }}"
