---
- name: Launch benchmark for kubecontrol with one pod per job
  hosts: cloudcontroller
  become: true
  roles:
    - role: k8s_job_deploy
      vars:
        app_k8s_job_deploy_layout: single_parallel
        app_k8s_job_deploy_env:
          - name: SLEEP_TIME
            value: "{{ sleep_time }}"
