---
- name: Launch benchmark for kube_kata with one kubectl command call per job
  hosts: cloudcontroller
  become: true
  roles:
    - role: k8s_job_deploy
      vars:
        app_k8s_job_deploy_layout: per_file_direct
        app_k8s_job_deploy_env:
          - name: SLEEP_TIME
            value: "{{ sleep_time }}"
