---
- hosts: base_cloud
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Add cloud user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: true

    - name: Allow HTTP pulling from private docker registry
      shell: echo '{ "insecure-registries":["{{ registry_ip }}"] }' > /etc/docker/daemon.json

    - name: Restart docker service
      command: systemctl restart docker

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Make sure swap is disabled even after reboot
      command: sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Enable ipv4 forwarding
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

    - name: Reload ip settings
      command: sysctl -p

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    # Use this version with KubeEdge 1.6.1
    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - kubelet=1.21.0-00
          - kubeadm=1.21.0-00
          - kubectl=1.21.0-00

    - name: Get KubeEdge and unarchive it
      unarchive:
        src: https://github.com/kubeedge/kubeedge/releases/download/v1.8.1/keadm-v1.8.1-linux-amd64.tar.gz
        dest: /tmp
        remote_src: true

    - name: Make KubeEdge executable
      file:
        dest: /tmp/keadm-v1.8.1-linux-amd64/keadm/keadm
        mode: +x

    - name: Move KubeEdge executable
      command: mv "/tmp/keadm-v1.8.1-linux-amd64/keadm/keadm" /usr/local/bin

    - name: Remove unneeded KubeEdge files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/keadm-v1.8.1-linux-amd64
        - /tmp/keadm-v1.8.1-linux-amd64.tar.gz
