---
rm_kubeedge_cloudcore_cloud_ip: >-
  {{ cloud_ip | default(continuum_cloud_ip | default('')) }}
rm_kubeedge_cloudcore_username: >-
  {{ username | default(continuum_username | default('ubuntu')) }}
rm_kubeedge_cloudcore_continuum_home: "{{ continuum_home | default('/tmp') }}"
rm_kubeedge_cloudcore_kubeversion: "{{ kubeversion | default(continuum_kubeversion | default('1.27.0')) }}"
rm_kubeedge_cloudcore_kubeedge_version: "1.22.0"
