---
rm_k8s_observability_repo: https://github.com/prometheus-operator/kube-prometheus.git
rm_k8s_observability_version: release-0.13
rm_k8s_observability_path: /kube-prometheus
rm_k8s_observability_cloud_ip: >-
  {{ cloud_ip | default(continuum_cloud_ip | default('127.0.0.1')) }}
rm_k8s_observability_cloud_ip_external: >-
  {{ cloud_ip_external | default(continuum_cloud_ip_external |
  default(rm_k8s_observability_cloud_ip)) }}
