---
rm_kata_containers_version: "3.1.3"
rm_kata_containers_use_overlayfs: "{{ continuum_use_overlayfs | default(false) }}"
rm_kata_containers_registry_ip: >-
  {{ registry_ip | default(continuum_registry_ip | default('')) }}
rm_kata_containers_username: >-
  {{ username | default(continuum_username | default('ubuntu')) }}
rm_kata_containers_jaeger_image: "jaegertracing/all-in-one:1.47"
rm_kata_containers_jaeger_container_name: "jaeger"
