---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Checkout Opencraft
      git:
        repo: 'https://github.com/atlarge-research/opencraft-dev.git'
        version: '27-building-dockerfile-fails' # TODO: once merged, change to dev
        dest: '/tmp/opencraft'

    - name: Add configuration file to dockerfile
      blockinfile:
        path: 'tmp/opencraft/Dockerfile'
        inserbefore: 'CMD ["java", "-jar", "opencraft.jar"]'
        block: 'COPY ./opencraft.yml /config/opencraft.yml'

    - name: Build and push image
      shell: 'docker buildx build --platform linux/amd64,linux/arm64 -t lwagner1/minecraft_benchmark:minecraft_server --push .'
