---
- hosts: all_hosts
  tasks:
    - name: Remove old base image from {{ base_path }}/.continuum/images
      shell: |
        rm -f "{{ base_path }}/.continuum/images/{{ base }}.qcow2"

    - name: Create base image
      command: >
        qemu-img create -f qcow2 -F qcow2 -b "{{ base_path }}/.continuum/images/ubuntu2004.qcow2"
        "{{ base_path }}/.continuum/images/{{ base }}.qcow2"

    - name: Install cloudinit requirements
      package:
        name: cloud-image-utils
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install cloudinit requirements
      package:
        name: cloud-utils
        state: present
      vars:
        ansible_python_interpreter: "/usr/bin/python"
      when: ansible_os_family == "RedHat"

    - name: Add cloudinit disk for base
      command: >
        cloud-localds "{{ base_path }}/.continuum/images/user_data_{{ base }}.img"
        "{{ base_path }}/.continuum/user_data_{{ base }}.yml"
