---
- hosts: clouds
  tasks:
    - name: Create cloud controller image
      shell: |
        if [ "{{ cloud_controller }}" -gt "0" ]; then
          qemu-img create -f qcow2 -F qcow2 \
          -b "{{ base_path }}/.continuum/images/{{ base_cloud }}.qcow2" \
          "{{ base_path }}/.continuum/images/cloud_controller_{{ username }}.qcow2"
        fi

    - name: Create cloud images
      shell: |
        for i in $(seq "{{ cloud_start }}" "{{ cloud_end }}"); do
          qemu-img create -f qcow2 -F qcow2 \
          -b "{{ base_path }}/.continuum/images/{{ base_cloud }}.qcow2" \
          "{{ base_path }}/.continuum/images/cloud${i}_{{ username }}.qcow2" 50G
        done

    - name: Add cloudinit disk for cloud controller
      shell: |
        if [ "{{ cloud_controller }}" -gt "0" ]; then
          cloud-localds "{{ base_path }}/.continuum/images/user_data_cloud_controller_{{ username }}.img" \
          "{{ base_path }}/.continuum/user_data_cloud_controller_{{ username }}.yml"
        fi

    - name: Add cloudinit disk for cloud
      shell: |
        for i in $(seq "{{ cloud_start }}" "{{ cloud_end }}"); do
          cloud-localds "{{ base_path }}/.continuum/images/user_data_cloud${i}_{{ username }}.img" \
          "{{ base_path }}/.continuum/user_data_cloud${i}_{{ username }}.yml"
        done
