---
- name: Launch benchmark for kubeedge with one call, and one job per file
  hosts: cloudcontroller
  become: true
  roles:
    - role: k8s_job_deploy
      vars:
        app_k8s_job_deploy_layout: one_file_per_job
        app_k8s_job_deploy_apply: true
        app_k8s_job_deploy_pull_policy: Always
        app_k8s_job_deploy_ports:
          - 1883
        app_k8s_job_deploy_env:
          - name: MQTT_LOCAL_IP
            value_from_field_path: status.hostIP
          - name: MQTT_LOGS
            value: "{{ mqtt_logs }}"
          - name: CPU_THREADS
            value: "{{ cpu_threads }}"
          - name: ENDPOINT_CONNECTED
            value: "{{ endpoint_connected }}"
